package com.utstatus.gui;

import com.google.common.base.Charsets;
import static com.google.common.base.Strings.isNullOrEmpty;
import com.google.common.io.Files;
import com.google.common.primitives.Ints;
import com.utstatus.Driver;
import com.utstatus.model.Configuration;
import com.utstatus.persistence.ConfigurationParser;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author dcnorris
 */
public class Setup extends javax.swing.JFrame {
    
    private static final Logger logger = LoggerFactory.getLogger(Setup.class);
    
    private JFileChooser exeChooser;
    private Configuration config;
    private UrtApp app;
    private ServerSelectionView ssv;
    
    public Setup(Configuration config, UrtApp app) {
        this.config = config;
        this.app = app;
        initFileChooser();
        ssv = new ServerSelectionView();
        initComponents();
    }
    
    private void initFileChooser() {
        exeChooser = new JFileChooser();
        exeChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        exeChooser.setDialogTitle("Open Index Folder ...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ipAddressTextField = new javax.swing.JTextField();
        portTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        playerNameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        exeTextField = new javax.swing.JTextField();
        exeBrowseBtn = new javax.swing.JButton();
        errorNotification = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        masterServerMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        portTextField.setText(config.getPortString());

        jLabel1.setText("Server IP Address:");

        jLabel2.setText("Server Port:");

        jLabel3.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/urbanterror.jpg")));

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("PlayerName:");

        jLabel5.setText("Path to Executable:");

        exeBrowseBtn.setText("Browse...");
        exeBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exeBrowseBtnActionPerformed(evt);
            }
        });

        errorNotification.setForeground(new java.awt.Color(255, 0, 0));
        errorNotification.setText("warning");

        jMenu1.setText("File");

        jMenuItem1.setText("exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        viewMenu.setText("View");

        masterServerMenuItem.setText("view available servers");
        masterServerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterServerMenuItemActionPerformed(evt);
            }
        });
        viewMenu.add(masterServerMenuItem);

        jMenuBar1.add(viewMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ipAddressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(portTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(playerNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(exeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))
                    .addComponent(exeBrowseBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(errorNotification)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(playerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(exeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exeBrowseBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(errorNotification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        ipAddressTextField.setText(config.getIp());
        playerNameTextField.setText(config.getPlayerName());
        exeTextField.setText(config.getExecutablePath());
        errorNotification.setText("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if (isValidInput()) {
            config.setIp(ipAddressTextField.getText());
            config.setPort(Integer.parseInt(portTextField.getText()));
            config.setPlayerName(playerNameTextField.getText());
            config.setExecutablePath(exeTextField.getText());
            setVisible(false);
        }
        try {
            Files.write(ConfigurationParser.toJson(config), new File(System.getProperty("user.home"), Driver.CONFIGURATION_FILE_NAME), Charsets.UTF_8);
        } catch (IOException ex) {
            logger.error("Error persisting configuration", ex);
        }
        
        app.initScheduler();
        app.setVisible(true);
    }//GEN-LAST:event_startButtonActionPerformed

    private void exeBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exeBrowseBtnActionPerformed
        exeChooser.showDialog(this, "Open");
        File f = exeChooser.getSelectedFile();
        if (f == null) {
            exeTextField.setText("");
            return;
        }
        exeTextField.setText(f.getAbsolutePath());
    }//GEN-LAST:event_exeBrowseBtnActionPerformed

    private void masterServerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterServerMenuItemActionPerformed
        ssv.setVisible(true);
    }//GEN-LAST:event_masterServerMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorNotification;
    private javax.swing.JButton exeBrowseBtn;
    private javax.swing.JTextField exeTextField;
    private javax.swing.JTextField ipAddressTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem masterServerMenuItem;
    private javax.swing.JTextField playerNameTextField;
    private javax.swing.JTextField portTextField;
    private javax.swing.JButton startButton;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables

    private boolean isValidInput() {
        if (isNullOrEmpty(ipAddressTextField.getText())
                && isNullOrEmpty(portTextField.getText())
                && isNullOrEmpty(playerNameTextField.getText())
                && isNullOrEmpty(exeTextField.getText())) {
            try {
                Ints.tryParse(portTextField.getText());
            } catch (Exception ex) {
                errorNotification.setText("Enter a valid Port");
                return false;
            }
            errorNotification.setText("Please Enter all Fields.");
            return false;
        }
        return true;
    }
    
}
